export const REQUEST_PLAYERS = 'REQUEST_PLAYERS'
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const ERROR_FETCHING_PLAYERS = 'ERROR_FETCHING_PLAYERS'